// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7jTaeSbu-aonJpbDWsuJfaDFnFINf6wU',
    appId: '1:157682941490:web:8ece00eca4ac360d58062b',
    messagingSenderId: '157682941490',
    projectId: 'fittek-8c745',
    authDomain: 'fittek-8c745.firebaseapp.com',
    storageBucket: 'fittek-8c745.appspot.com',
    measurementId: 'G-T712BWQWTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgco6HU6SQFbBxQCIwAwfb9EGTTTmtwXY',
    appId: '1:157682941490:android:6300aefff1a892d958062b',
    messagingSenderId: '157682941490',
    projectId: 'fittek-8c745',
    storageBucket: 'fittek-8c745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAtoOoj2g0Mc4Bu4Rqwu1tzR3jH8ucaQo',
    appId: '1:157682941490:ios:80db7634540e60ad58062b',
    messagingSenderId: '157682941490',
    projectId: 'fittek-8c745',
    storageBucket: 'fittek-8c745.appspot.com',
    iosClientId: '157682941490-2f17gvd4v1v27iuujggg7qv8purgcu12.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAtoOoj2g0Mc4Bu4Rqwu1tzR3jH8ucaQo',
    appId: '1:157682941490:ios:80db7634540e60ad58062b',
    messagingSenderId: '157682941490',
    projectId: 'fittek-8c745',
    storageBucket: 'fittek-8c745.appspot.com',
    iosClientId: '157682941490-2f17gvd4v1v27iuujggg7qv8purgcu12.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittek',
  );
}
